### ISSUE TITLE
FE: 게시글 상세 페이지 구현 (디자인,레이아웃 포함)

### ISSUE THREAD

**Issue by devfrank9** [ProjectCoco/coco#12]
## 개요
게시글 상세 페이지 구현

## 소요시간
~2022.05.13

## 디자인선정
<img width="672" alt="image" src="https://user-images.githubusercontent.com/90244663/168590375-78bc2833-a0a4-4a9b-aceb-9bf5cf1837fa.png">
made by @JEONGHWANMIN 

## 진행사항
- [x] 게시글 상세 페이지 코드 작성 완료
- [ ] PR로 커밋메세지 첨부해서 업로드
- [ ] 해당 이슈번호 태깅해서 closed

**Comment by devfrank9** [comment]
만약 frontend에서 파생된 브랜치를 현 이슈 PR이전에서 가져왔다면,
작업중인 파일이 있을경우 따로 로컬에 백업 후
다시 frontend에서 브랜치 따온 후 가져와서 작업하시기 바랍니다.

**Comment by JEONGHWANMIN** [comment]
확인했습니다 ~
